[GLOBAL]
pants_version = "2.18.0rc5"
backend_packages = [
  "pants.backend.python",
  "pants.backend.google_cloud_function.python",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ['==3.11.*']
enable_resolves = true

[python-infer]
use_rust_parser = true
